# Site settings
title: Net Zero House
email: max@bernsteinbear.com
description: "Objective: passive house certification"
baseurl: "/netzero.io"
url: "http://netzero.io"

# Build settings
markdown: kramdown
permalink: pretty
